// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0IUB-X-FOj3qhNnjJrHFNy-CnRL3d7Rg',
    appId: '1:431072518233:web:db2a590f12d787d2ae5148',
    messagingSenderId: '431072518233',
    projectId: 'binergy-d0b96',
    authDomain: 'binergy-d0b96.firebaseapp.com',
    storageBucket: 'binergy-d0b96.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkcowWlvga-6gtgvvVpk6BvNC1UpVwjVI',
    appId: '1:431072518233:android:85c48297d3392987ae5148',
    messagingSenderId: '431072518233',
    projectId: 'binergy-d0b96',
    storageBucket: 'binergy-d0b96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZHFCWQRpfotr4xHkWI-T_q_h5i4D2I30',
    appId: '1:431072518233:ios:26f5d57751d2e8c8ae5148',
    messagingSenderId: '431072518233',
    projectId: 'binergy-d0b96',
    storageBucket: 'binergy-d0b96.appspot.com',
    iosClientId: '431072518233-mfu1r45bae0asd2e0108f1gnj5e2ftim.apps.googleusercontent.com',
    iosBundleId: 'com.example.binergy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZHFCWQRpfotr4xHkWI-T_q_h5i4D2I30',
    appId: '1:431072518233:ios:1bc9a7e48dcf9083ae5148',
    messagingSenderId: '431072518233',
    projectId: 'binergy-d0b96',
    storageBucket: 'binergy-d0b96.appspot.com',
    iosClientId: '431072518233-l6b68pcq1i8c19v5ltirfe2jopolmeiu.apps.googleusercontent.com',
    iosBundleId: 'com.example.binergy.RunnerTests',
  );
}
